const newSpace = {
  name: 'myspace',
  description: 'this is my description',
  const: 23454.40,
  capacity: 4,
  open: true,
  ground_rules: 'dont do bad things',
  street_address: '748 camp st',
  city: 'New Orleans',
  zip: 70115,
  state: 'LA',
  neighborhood: 'garden district',
  owner_fb_id: 'sadf9pwp8rypf98dsiyr9pfeouyfasfasd',
  purpose_id: 1,
  timeline_id: 2,
  pet_id: 3,
  smoking_id: 2,
}

const newUser = {
  about: 'i\'m me! and no one else. except for sometimes',
  image_url: 'https://i.chzbgr.com/full/9013910528/hAB49129F/',
  name_first: 'bobo',
  name_last: 'boberton',
  phone: 555555555555,
  email: 'email@email.email',
  fb_id: 'sadf9pwp8rypf98dsiyr9pfeouyfasfasd',
  fb_link: 'facebook.com',
  fb_verified: false,
  searchable_work: true,
  searchable_live: true,
  profession: 'programmer',
  birthdate: new Date(),
  gender_id: 2,
  sleep_id: 1,
  personality_id: 1,
};

const newSearch = {
  price_min: 500.00,
  price_max: 500.00,
  age_min: 20,
  age_max: 30,
  location_specificity: 'this is the specificity from geocoding',
  location_search: 'this is exactly what the user typed!',
  zip: '70118',
  city: 'New Orleans',
  state: 'la',
  include_people: true,
  fb_id: 'sadf9pwp8rypf98dsiyr9pfeouyfasfasd',
  personality_id: 2,
  sleep_id: 2,
  purpose_id: 1,
  timeline_id: 2,
  pet_id: 3,
  smoking_id: 3,
};
