const newUser = {
  about: 'i\'m me! and no one else. except for sometimes',
  image_url: 'https://i.chzbgr.com/full/9013910528/hAB49129F/',
  name_first: 'bobo',
  name_last: 'boberton',
  phone: '555555555555',
  email: 'email@email.email',
  fb_id: 'sadf9pwp8rypf98dsiyr9pfeouyf',
  fb_link: 'facebook.com',
  fb_verified: false,
  searchable_work: false,
  searchable_live: false,
  planet: 'Uranus',
  birthdate: new Date(),
  gender_id: 0,
  sleep_id: 1,
  personalit_id: 1,
};
