const newUser = {
  about: 'i\'m me! and no one else. except for sometimes',
  image_url: 'https://i.chzbgr.com/full/9013910528/hAB49129F/',
  name_first: 'bobo',
  name_last: 'boberton',
  phone: 555555555555,
  email: 'email@email.email',
  fb_id: 'sadf9pwp8rypf98dsiyr9pfeouyf',
  fb_link: 'facebook.com',
  fb_verified: false,
  searchable_work: false,
  searchable_live: false,
  profession: 'programmer',
  birthdate: new Date(),
  gender_id: 2,
  sleep_id: 1,
  personality_id: 1,
};

const newSearch = {
  price_min: 500.00,
  price_max: 500.00,
  location_specificity: 'this is the specificity from geocoding',
  location_search: 'this is exactly what the user typed!',
  zip: '70118',
  city: 'New Orleans',
  state: 'la',
  include_people: true,
  user_id: 2,
  gender_id: 1,
  personality_id: 2,
  sleep_id: 2,
  purpose_id: 1,
  timeline_id: 2,
  pet_id: 3,
  smoking_id: 3,
};
